import com.viewol.util.CiecImpl;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lenovo' at '18-6-27 下午1:35' with Gradle 2.14.1
 *
 * @author lenovo, @date 18-6-27 下午1:35
 */
public class LibraryTest {
   
}
