import com.viewol.util.CiecImpl;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lenovo' at '18-6-27 下午1:35' with Gradle 2.14.1
 *
 * @author lenovo, @date 18-6-27 下午1:35
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }


    public static void main(String[] args) throws Exception{

        CiecImpl ciec = new CiecImpl();
        System.out.println(ciec.getUserFromNobile("13810436365"));

//        String jsoncommond ="{"
//                +"\"request\":{"
//                +" \"aPPID\":\"xiaof\","
//                +" \"aPPKEY\":\"xiaof1w2E#R$\","
//                +" \"command\":\"rslistvinfozz\","
//                +" \"openID\":\"1\","
//                + "\"source\":\"WEB\","
//                +" \"projno\":\"91819\""
//                +" }," +"\"data\":{"
//                +" \"SPECT_MOBILE\":\"18601156219\""
//                +" } }";
////        String jsoncommond ="{"
////                +"\"request\":{"
////                +" \"aPPID\":\"xiaof\","
////                +" \"aPPKEY\":\"xiaof1w2E#R$\","
////                +" \"command\":\"rslistvinfozza\","
////                +" \"openID\":\"12345667\","
////                + "\"source\":\"WEB\","
////                +" \"projno\":\"91819\""
////                +" }," +"\"data\":{"
////                +" \"SPECT_REC_NO\":\"0\"}}";
//
//
//        System.out.println(jsoncommond);
//
//        CloseableHttpClient httpclient = HttpClients.createDefault();
//        HttpPost httpPost = new HttpPost("http://weixin.ciec.com.cn:8080/ciecWS/sAPICall");
//        List nvps = new ArrayList();
//        nvps.add(new BasicNameValuePair("jsoncommond", jsoncommond));
//
//        httpPost.setEntity(new UrlEncodedFormEntity(nvps, "UTF-8"));
//        CloseableHttpResponse response = httpclient.execute(httpPost);
//        HttpEntity entity = response.getEntity();
//        String APIresult = "";
//        if (entity != null) {
//            APIresult = EntityUtils.toString(entity, "utf-8");
//        }
//        System.out.println(APIresult);
//        EntityUtils.consume((org.apache.http.HttpEntity) entity);
//        response.close();
//        response.close();
//        httpclient.close();

    }
}
